#==============================================================================
# Boot setup
# Bootloader etc.
#==============================================================================

# Install intel microcode if CPU vendor is Intel
- name: Add intel-ucode if needed
  command: arch-chroot /mnt pacman -S intel-ucode --noconfirm
  when: '"Intel" in cpu_vendor'

- name: Adjust mkinitcpio hooks
  lineinfile:
    dest: /mnt/etc/mkinitcpio.conf
    regexp: ^HOOKS
    line: HOOKS=(base systemd autodetect modconf block filesystems keyboard sd-vconsole btrfs)
  tags:
    - initramfs

- name: Re-generate initframfs
  command: arch-chroot /mnt mkinitcpio -p linux
  tags:
    - initramfs

- name: Install and configure bootloader
  include_tasks:
    file: bootloader/{{ bootloader }}.yml
    apply:
      tags:
        - arch2disk
        - boot_setup
        - bootloader
  tags:
    - arch2disk
    - boot_setup
    - bootloader
