#==============================================================================
# System localization
#==============================================================================

- name: Set timezone
  command: arch-chroot /mnt ln -sf /usr/share/zoneinfo/{{ timezone }} /etc/localtime
  args:
    creates: /etc/localtime
  tags:
    - set_time

- name: Set hardware clock  # noqa no-changed-when
  command: arch-chroot /mnt hwclock --systohc
  tags:
    - set_time

- name: Generate locales, step 1/2
  replace:
    path: /mnt/etc/locale.gen
    regexp: ^\s*#\s*({{ locales|join('|') }})(.*)$
    replace: \1\2
  tags:
    - locales

- name: Generate locales, step 2/2  # noqa no-changed-when
  command: arch-chroot /mnt locale-gen
  tags:
    - locales

- name: Set system language
  template:
    dest: /mnt/etc/locale.conf
    src: etc/locale.conf
    mode: 0644
    group: root
    owner: root
  tags:
    - locales

- name: Set keymap
  template:
    dest: /mnt/etc/vconsole.conf
    src: etc/vconsole.conf
    mode: 0644
    group: root
    owner: root
  tags:
    - keymap
