#==============================================================================
# Main task file
#==============================================================================

# This tasks helps to warrant idempotency, which is always assumed by Ansible
- name: Abort if the host is not booted from the Arch install media
  fail:
    msg: "This host is not booted from the Arch install media!"
  when: ansible_nodename != 'archiso'
  tags:
    - arch2disk
    - boot_check
    - quick_exit

- name: Synchronize clock via NTP
  command: timedatectl set-ntp true
  tags:
    - arch2disk
    - sync_clock

# This sets some derive facts from ansible_facts and role variables
- name: Set derived facts
  include_tasks:
    file: derive_facts.yml
    apply:
      tags:
        - arch2disk
        - derive_facts
  tags:
    - arch2disk
    - derive_facts

- name: Include partitioning tasks
  include_tasks:
    file: partitioning.yml
    apply:
      tags:
        - arch2disk
        - partitioning
  tags:
    - arch2disk
    - partitioning

- name: Update pacman DB and install rankmirrors
  pacman:
    name: pacman-contrib
    update_cache: yes  # Update pacman database, also needed for pacstrap
  tags:
    - arch2disk

# Would be nice to have a script doing this without a country code
# AUR pkg rate-arch-mirrors takes too long to compile+install...
- name: Use rankmirrors to filter the fastest mirrors that support HTTPS
  shell: >
    curl -s "https://archlinux.org/mirrorlist/?protocol=https&use_mirror_status=on&country={{ locale_country|upper }}"
    | sed -e 's/^#Server/Server/' -e '/^#/d'
    | rankmirrors -n 5 -
    > /etc/pacman.d/mirrorlist
  args:
    warn: false
  tags:
    - arch2disk
    - mirrors

- name: Install base system to new root
  # Install with pacstrap
  # yes "" | == always pressing the enter key whenever a question is asked
  # That way always the defaults are chosen
  command: >
    pacstrap /mnt base
    wget git nano vim
    efibootmgr efitools
    linux linux-firmware sudo
    openssh networkmanager
    python pyalpm
    dosfstools btrfs-progs
    --noprogressbar
  tags:
    - arch2disk
    - pacstrap

- name: Install base development tools
  # pacstrap doesn't like groups
  shell: arch-chroot /mnt bash -c "yes '' | pacman -S base-devel --noconfirm"
  tags:
    - arch2disk
    - pacstrap
    - base_devel

# I now about the Ansible module to do this
# But that would need about a thousands lines more, and is more error-prone
# TODO this didn't work in test...
- name: Generate fstab
  shell: genfstab -U /mnt >> /mnt/etc/fstab
  tags:
    - arch2disk
    - fstab

- name: System localization
  include_tasks:
    file: localization.yml
    apply:
      tags:
        - arch2disk
        - localization
  tags:
    - arch2disk
    - localization

- name: Install fonts
  include_tasks: fonts.yml
  tags:
    - arch2disk
    - fonts

- name: Networking
  include_tasks:
    file: networking.yml
    apply:
      tags:
        - arch2disk
        - networking
  tags:
    - arch2disk
    - networking

- name: Initial user setup
  include_tasks:
    file: user_setup.yml
    apply:
      tags:
        - arch2disk
        - user_setup
  tags:
    - arch2disk
    - user_setup

- name: Boot setup
  include_tasks:
    file: boot_setup.yml
    apply:
      tags:
        - arch2disk
        - boot_setup
  tags:
    - arch2disk
    - boot_setup

- name: Reboot the machine
  reboot:
  tags:
    - arch2disk
    - boot_setup
    - reboot

- name: Install pikaur
  # Install pikaur using pikaur
  shell: |
    cd /tmp
    git clone https://github.com/actionless/pikaur.git
    cd pikaur
    python3 ./pikaur.py -S pikaur --noconfirm
  args:
    creates: /usr/bin/pikaur
  tags:
    - arch2disk
    - pikaur
