#==============================================================================
# Main task file
#==============================================================================

# This tasks helps to warrant idempotency, which is always assumed by Ansible
- name: Abort if the host is not booted from the Arch install media
  fail:
    msg: "This host is not booted from the Arch install media!"
  when: ansible_nodename != 'archiso'
  tags:
    - arch2disk
    - boot_check
    - quick_exit

- name: Synchronize clock via NTP  # noqa no-changed-when
  command: timedatectl set-ntp true
  tags:
    - arch2disk
    - sync_clock

# This sets some derive facts from ansible_facts and role variables
- name: Set derived facts
  include_tasks:
    file: derive_facts.yml
    apply:
      tags:
        - arch2disk
        - derive_facts
  tags:
    - arch2disk
    - derive_facts

- name: Include partitioning tasks
  include_tasks:
    file: partitioning.yml
    apply:
      tags:
        - arch2disk
        - partitioning
  tags:
    - arch2disk
    - partitioning

- name: Update pacman DB and install rankmirrors
  pacman:
    name: pacman-contrib reflector
    update_cache: yes  # Update pacman database, also needed for pacstrap
  tags:
    - arch2disk

- name: Use reflector to filter the fastest mirrors that support HTTPS # noqa no-changed-when
  shell: >
    reflector -p https --age 12 --sort rate --score 15 -f 10 --save /etc/pacman.d/mirrorlist
  args:
    warn: false
  tags:
    - arch2disk
    - mirrors

- name: Install base system to new root
  # Install with pacstrap
  # yes "" | == always pressing the enter key whenever a question is asked
  # That way always the defaults are chosen
  command: >
    pacstrap /mnt base
    pacman-contrib reflector
    wget git nano vim
    efibootmgr efitools
    linux linux-firmware sudo
    openssh networkmanager
    python pyalpm python-psutil
    dosfstools btrfs-progs
    --noprogressbar
  args:
    creates: /mnt/usr/bin/nano  # Among others of course...
  tags:
    - arch2disk
    - pacstrap

# Overwrite mirrorlist with custom one
- name: Use reflector to filter the fastest mirrors that support HTTPS # noqa no-changed-when
  shell: >
    reflector -p https --age 12 --sort rate --score 15 -f 10 --save /etc/pacman.d/mirrorlist
  tags:
    - arch2disk
    - mirrors

- name: Install base development tools # noqa risky-shell-pipe
  # pacstrap doesn't like groups
  shell: arch-chroot /mnt bash -c "yes '' | pacman -S base-devel --noconfirm"
  args:
    creates: /mnt/usr/bin/make  # One of the things installed...
  tags:
    - arch2disk
    - pacstrap
    - base_devel

# I now about the Ansible module to do this
# But that would need about a thousands lines more, and is more error-prone
- name: Generate fstab
  shell: genfstab -U /mnt >> /mnt/etc/fstab
  # TODO this task doesn't warrant idempotency
  tags:
    - arch2disk
    - fstab

# Make sure the hook dir exists
- name: Ensure pacman hook dir existance
  file:
    path: /etc/pacman.d/hooks/
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - arch2disk

- name: System localization
  include_tasks:
    file: localization.yml
    apply:
      tags:
        - arch2disk
        - localization
  tags:
    - arch2disk
    - localization

- name: Install fonts
  include_tasks: fonts.yml
  tags:
    - arch2disk
    - fonts

- name: Networking
  include_tasks:
    file: networking.yml
    apply:
      tags:
        - arch2disk
        - networking
  tags:
    - arch2disk
    - networking

- name: Initial user setup
  include_tasks:
    file: user_setup.yml
    apply:
      tags:
        - arch2disk
        - user_setup
  tags:
    - arch2disk
    - user_setup

- name: Boot setup
  include_tasks:
    file: boot_setup.yml
    apply:
      tags:
        - arch2disk
        - boot_setup
  tags:
    - arch2disk
    - boot_setup

- name: Reboot the machine
  reboot:
  tags:
    - arch2disk
    - boot_setup
    - reboot

- name: Post reboot tasks
  include_tasks:
    file: post_reboot.yml
    apply:
      tags:
        - arch2disk
        - post_reboot
