#==============================================================================
# System networking
#==============================================================================

- name: Set hostname
  template:
    dest: /mnt/etc/hostname
    src: etc/hostname
    mode: 0644
    group: root
    owner: root
  tags:
    - arch2disk
    - networking
    - hostname

- name: Copy /etc/hosts
  template:
    dest: /mnt/etc/hosts
    src: etc/hosts
    mode: 0644
    group: root
    owner: root
  tags:
    - arch2disk
    - networking
    - hostname

- name: Creating a file with content
  tags:
    - arch2disk
    - networking
    - networkmanager
    - WiFi
    copy:
      dest: "/mnt/etc/NetworkManager/conf.d/wifi_rand_mac.conf"
      content: |
        [device]
        wifi.scan-rand-mac-address=yes
        [connection-mac-randomization]
        wifi.cloned-mac-address=stable
# Enable NetworkManager
- name: Enable NetworkManager
  command: arch-chroot /mnt systemctl enable NetworkManager.service
  tags:
    - arch2disk
    - networking
    - networkmanager
