#==============================================================================
# System networking
#==============================================================================

- name: Set hostname
  template:
    dest: /mnt/etc/hostname
    src: etc/hostname
    mode: 0644
    group: root
    owner: root
  tags:
    - arch2disk
    - networking
    - hostname

- name: Copy /etc/hosts
  template:
    dest: /mnt/etc/hosts
    src: etc/hosts
    mode: 0644
    group: root
    owner: root
  tags:
    - arch2disk
    - networking
    - hostname

# Enable NetworkManager
- name: Enable NetworkManager
  systemd:
    name: NetworkManager.service
    enabled: yes
    masked: no
  tags:
    - arch2disk
    - networking
    - networkmanager
