#==============================================================================
# System networking
#==============================================================================

- name: Set hostname
  template:
    dest: /mnt/etc/hostname
    src: etc/hostname
    mode: 0644
    group: root
    owner: root
  tags:
    - hostname

- name: Copy /etc/hosts
  template:
    dest: /mnt/etc/hosts
    src: etc/hosts
    mode: 0644
    group: root
    owner: root
  tags:
    - hostname

- name: Configure MAC randomizing in NM
  copy:
    dest: "/mnt/etc/NetworkManager/conf.d/wifi_rand_mac.conf"
    content: |
      [device]
      wifi.scan-rand-mac-address=yes
      [connection-mac-randomization]
      wifi.cloned-mac-address=stable
  tags:
    - networkmanager
    - wifi

# Enable NetworkManager
- name: Enable NetworkManager
  command: arch-chroot /mnt systemctl enable NetworkManager.service
  tags:
    - networkmanager

- name: Copy NetworkManager static IP config
  template:
    dest: /mnt/etc/NetworkManager/system-connections/temp-setup.nmconnection
    src: etc/NetworkManager/system-connections/temp-setup.nmconnection
    mode: 0600
    group: root
    owner: root
  tags:
    - networkmanager
    - static_ip

# Enable SSH server
- name: Enable sshd
  command: arch-chroot /mnt systemctl enable sshd
  tags:
    - sshd
