#==============================================================================
#  Post-reboot tasks
# These tasks can't run before reboot because of various reasons
#==============================================================================

# Reset network to normal .....................................................
- name: Copy auto connection profile
  template:
    dest: /etc/NetworkManager/system-connections/auto.nmconnection
    src: etc/NetworkManager/system-connections/auto.nmconnection
    mode: 0600
    group: root
    owner: root
  tags:
    - networkmanager

- name: Delete temporary network connection profile
  file:
    state: absent
    path: /etc/NetworkManager/system-connections/temp-setup.nmconnection

- name: Synchronize clock via NTP  # noqa no-changed-when
  command: timedatectl set-ntp true

# Install AUR packages ........................................................
- name: Install pikaur
  # Install pikaur using pikaur
  shell: |
    cd /tmp
    git clone https://github.com/actionless/pikaur.git
    cd pikaur
    python3 ./pikaur.py -S pikaur --noconfirm
  args:
    creates: /usr/bin/pikaur

- name: Install systemd-boot update transaction hook
  aur:
    name: systemd-boot-pacman-hook
    use: pikaur
  when: bootloader=="systemd-boot"
