#==============================================================================
# Users
# Set root passwd
# Add initial user
#==============================================================================

- name: Create random root password
  set_fact:
    rootpasswd: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') }}"
  when: rootpasswd | default('', true) | length == 0
  tags:
    - root_passwd

- name: Set root password
  user:
    name: root
    password: "{{ rootpasswd | password_hash('sha512') }}"
  tags:
    - root_passwd

- name: Create root .ssh dir if needed
  file:
    path: /mnt/root/.ssh
    state: directory
    mode: 0700
    owner: root
    group: root
  when: root_copy_allowed_keys
  tags:
    - root_ssh

- name: Copy SSH archiso key for root user
  copy:
    remote_src: true  # Copy from remote machine
    src: /root/.ssh/authorized_keys
    dest: /mnt/root/.ssh/authorized_keys
    mode: 0600
    owner: root
    group: root
  when: root_copy_allowed_keys
  tags:
    - root_ssh

# TODO add option for initial user, allow him to sudo and SSH logon with key
