# GENERAL =====================================================================
# Where to install ArchLinux to (block device, e.g. /dev/sda)
install_device: /dev/sda

# PARTITIONS AND FILESYSTEM ===================================================
# Swap partition size in MiB
# Set to 0 to disable swap
swap_size: "{{ ansible_facts['memtotal_mb'] }}"
# EFI partition size in Mib
efi_size: 1000
# Btrfs: transparent zstd compression level (integer, 1-9)
btrfs_compression_level: 6

# Localization ================================================================
# Code of your country, e.g. "de" or "fr"
locale_country: de
