# GENERAL =====================================================================
# Where to install ArchLinux to (block device, e.g. /dev/sda)
install_device: /dev/sda
# Choose a bootloader, currently only one supported:
# systemd-boot
bootloader: systemd-boot

# PARTITIONS AND FILESYSTEM ===================================================
# Swap partition size in MiB
# Set to 0 to disable swap
# By default this takes the RAM size
swap_size: "{{ ansible_facts['memtotal_mb'] }}"
# EFI partition size in Mib
efi_size: 1000
# Btrfs: transparent zstd compression level (integer, 1-9)
btrfs_compression_level: 6

# LOCALIZATION ================================================================
# Your country, identified by the internet TLD
# Used to find fast mirrors
locale_country: de
# Local timezone as in /usr/share/zoneinfo/
# Leave empty to use the timezone of the controller
timezone:
# Locales
# First locale is set as the system language
# The first an entry of the first column in /etc/locale.gen
locales:
  - de_DE.UTF-8
  - en_US
# The keymap to set for the system
# Tries to take the host keymap in case this variable is empty
keymap:

# NETWORKING ==================================================================
# Hostname; leave empty to derive it from a hashsum of MAC addresses
hostname:

# USERS =======================================================================
# Root password - leave empty to set a random password
rootpasswd:
# Whether to copy the allowed public keys of the archiso to the new root user
root_copy_authorized_keys: true
# Initial operational user to create
initial_user_name:
# Password of that user - leave empty for a random password
initial_user_pass:
