###############################################################################
# Install Gnome shell on wayland
###############################################################################

- name: Install wayland, gnome-shell and gdm
  pacman:
    name:
      - wayland
      - gdm
      - gnome-shell
  tags:
    - gnome_shell

- name: Disable gnome xsession
  command: mv /usr/share/xsessions/gnome.desktop /usr/share/xsessions/gnome.desktop.disabled
  args:
    removes: /usr/share/xsessions/gnome.desktop
  tags:
    - gnome_shell

- name: Set gnome keyboard layout
  dconf:
    key: "/org/gnome/desktop/input-sources"
    value: "['sources', [('xkb', 'de')]]"
  when: keymap|default('', true)|length == 0
  tags:
    - gnome_shell
    - keymap

- name: Enable and start gdm
  systemd:
    name: gdm
    state: started
    enabled: yes
  tags:
    - gnome_shell

- name: Install useful gnome desktop applications
  pacman:
    name:
      - gnome-shell-extension-appindicator
      - xdg-desktop-portal-gtk
      - xdg-user-dirs
      - nautilus
      - nautilus-sendto
  tags:
    - gnome_shell
    - apps
