name: fediverse-action
on:
  push:
    branches:
    - master
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: rzr/fediverse-action@master
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          host: "mastodon.online"