#==============================================================================
# Systemd-boot installation and configuration
#==============================================================================

- name: Install systemd-boot
  command: arch-chroot /mnt bootctl install
  # TODO add creates arg for the systemd-bootx64.efi this will create

# We let sytemd-boot load the linux kernel from the efi partition
# That way we avoid lots of problems

- name: Create loader dir
  file:
    path: /mnt/boot/loader
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Copy loader configuration
  template:
    dest: /mnt/boot/loader/loader.conf
    src: bootloader/systemd-boot/loader.conf
    mode: 0644
    group: root
    owner: root

- name: Create entries dir
  file:
    path: /mnt/boot/loader/entries
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Copy ArchLinux boot entry
  template:
    dest: /mnt/boot/loader/entries/arch.conf
    src: bootloader/systemd-boot/arch.conf
    mode: 0644
    group: root
    owner: root
